### ISSUE TITLE
Right-click on "Servos" blocks, "help" is disabled

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#911] opened 2018-11-30 09:09 UTC
**Describe the bug**
Right-click on "Servos" blocks, "help" is disabled

**Steps to reproduce the behavior**
1. Navigate to https://makecode.adafruit.com/beta#editor
2. Click "Advanced" -> "Extensions" -> choose "servo" to add
3. Click "Servos" in toolbox and right click on each block to check its help

**Expected behavior**
"Servos" blocks should have help tutorial

**Actual behavior**
Right-click on "Servos" blocks, "help" is disabled
![issue113002](https://user-images.githubusercontent.com/23466737/49279291-0d5f9200-f4c2-11e8-9483-d8b7076cd475.gif)

**Desktop (please complete the following information)**
OS: Windows
Browser: Edge, Chrome, Firefox & IE

**Additional context**
Adafruit Circuit Playground Express version:  1.2.9
Microsoft MakeCode version:  5.1.5
codal-circuit-playground runtime version:  v1.5.6

**Comment by abchatra** [comment] 2018-11-30 16:52
This is dupe of https://github.com/Microsoft/pxt-microbit/issues/1681

**Closed by abchatra** 2018-11-30 16:52 UTC
