### ISSUE TITLE
Some blocks are not convenient for user to input value

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#716] opened 2018-05-11 03:12 UTC
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Click "ADVANCED" -> "ARRAYS"
• Observe blocks on the opened window

**Expected result:**
All blocks should be convenient for user to input value
**Actual result:**
Some blocks are not convenient for user to input value
![123](https://user-images.githubusercontent.com/23466737/39904714-dec0a4e6-54c8-11e8-9718-8e13e94a1a5d.PNG)

**Comment by abchatra** [comment] 2018-06-07 05:40
This is by design. We don't the type of the list. It can be anything. Agree with you that is sub optimal experience. Won't fix from our end.

**Closed by abchatra** 2018-06-07 05:40 UTC
