### ISSUE TITLE
Serial editor not collapsing the same number

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt-adafruit#758] opened 2018-06-08 20:30 UTC
Console log in the serial editor doesn't collapse the same number value. 

Repro steps: 
- Add a console.log(5) in a forever loop 
- Check the serial editor log 

You'll see this: 
![screen shot 2018-06-08 at 1 27 20 pm](https://user-images.githubusercontent.com/16690124/41179599-15b48dc4-6b20-11e8-9c60-1ffc74933241.png)

Expected: 
- It should be collapsed.

**Comment by abchatra** [comment] 2018-06-10 16:56
Dupe of https://github.com/Microsoft/pxt-adafruit/issues/691

**Closed by abchatra** 2018-06-10 16:56 UTC
Labels: bug, component: serial
