### ISSUE TITLE
Shaking simulator works differently with clicking "SHAKE" button

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#660] opened 2018-03-09 08:23 UTC
**Repro steps**:
• Navigate to https://makecode.adafruit.com/beta
• Drag blocks as below .gif
• Click "SHAKE" button on simulator few times
• Shake simulator few times

**Expect result**:
When shaking simulator, it should work as clicking "SHAKE" button
![16](https://user-images.githubusercontent.com/23466737/37197477-d240fc2a-2372-11e8-922e-dafe31d72576.gif)

**Actual result**:
When shaking simulator, it only works once
![17](https://user-images.githubusercontent.com/23466737/37197483-d8c1135a-2372-11e8-913c-8e111c1fd81c.gif)

**Comment by abchatra** [comment] 2018-04-23 20:45
Dupe of https://github.com/Microsoft/pxt-adafruit/issues/626.

**Closed by abchatra** 2018-04-23 20:45 UTC
Labels: P2, bug

**Comment by Helen09** [comment] 2018-04-25 10:02
This issue is not same as https://github.com/Microsoft/pxt-adafruit/issues/626 , so please reopen it.

**Comment by samelhusseini** [comment] 2018-04-25 10:45
I get what's going on. Won't fix.
