### ISSUE TITLE
Logic Blocks can't be scrolled on IE

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#487] opened 2017-11-08 01:59 UTC
**Repro steps:**
## Issue 1
• Navigate to https://makecode.adafruit.com/beta
• Click "LOGIC"

**Expected result:**(Edge)
There should have scroll bar
![edge](https://user-images.githubusercontent.com/23497626/32489219-131cf628-c364-11e7-8e16-66b3150b9ed1.PNG)

**Actual result:**(Chrome,Firefox,IE)
There is no scroll bar
![ie](https://user-images.githubusercontent.com/23497626/32489225-1c44ccb2-c364-11e7-9c6c-17be79edde28.PNG)

## Issue2
• Navigate to https://makecode.adafruit.com/beta
• Click "LOGIC" and scroll down the blocks

**Expected result:**(Edge,Chrome, Firefox)
The blocks can be scrolled
![scroll](https://user-images.githubusercontent.com/23497626/32527872-e31fdca2-c3e4-11e7-8030-973f5b7789ab.gif)
**Actual result:**(IE)
The blocks can't be scrolled, and the blocks show imcomplete
![notscroll](https://user-images.githubusercontent.com/23497626/32527877-e88adc82-c3e4-11e7-89fd-b658e26f0682.gif)

**Comment by pelikhan** [comment] 2017-11-08 06:32
Great catch.

**Comment by microsoftsam** [comment] 2017-11-08 06:33
Fixed in https://github.com/Microsoft/pxt-adafruit/pull/486

**Comment by pelikhan** [comment] 2017-11-08 06:37
Still repro for me on last master.

**Comment by microsoftsam** [comment] 2017-11-08 06:41
Weird, it only repro's for the Logic category.. Interesting

**Comment by pelikhan** [comment] 2017-11-08 06:42
Only one with groups

**Comment by microsoftsam** [comment] 2017-11-08 06:42
Nah, light has groups as well.

**Comment by microsoftsam** [comment] 2017-11-08 06:44
Repro's on minecraft as well, so not really a recent regression. Very intriguing!!

**Comment by pelikhan** [comment] 2017-11-08 06:45
Works in Seeed

**Comment by microsoftsam** [comment] 2017-11-08 06:46
It doesn't work in Seeed for me

**Comment by pelikhan** [comment] 2017-11-08 06:49
right... IE...

**Comment by microsoftsam** [comment] 2017-11-08 06:50
This is not a Z-index issue or anything of that kind. Looks like a Blockly issue as the scrollbar is not even shown in the DOM. Will investigate further tomorrow

**Comment by microsoftsam** [comment] 2017-11-08 06:54
Repro's in the Blockly playground

**Comment by microsoftsam** [comment] 2017-11-08 08:32
Logic, External, Text and Arrays repro. So far I've narrowed down the issue to: 
- If / Else blocks 
- and any block that contains a get_variable block
If the category includes any of the above, it breaks the flyout height logic.

**Comment by microsoftsam** [comment] 2017-11-08 18:21
PXT-blockly issue: https://github.com/Microsoft/pxt-blockly/issues/84

Still investigating, but not only does the toolbox scrollbar break if the blocks listed above are in the Flyout, additionally, when any of those blocks are dragged into the workspace, they disappear as they're dragged. It's all connected, just gotta get to the root cause!

**Comment by microsoftsam** [comment] 2017-11-08 18:21
PXT-blockly issue: https://github.com/Microsoft/pxt-blockly/issues/84

Still investigating, but not only does the toolbox scrollbar break if the blocks listed above are in the Flyout, additionally, when any of those blocks are dragged into the workspace, they disappear as they're dragged. It's all connected, just gotta get to the root cause!

**Closed** 2017-11-09 01:22 UTC
Labels: bug, P1, release
