### ISSUE TITLE
Customer issue with InfraRed input

### ISSUE THREAD

**Issue by ladyada** [Microsoft/pxt-adafruit#580] opened 2017-12-20 16:12 UTC
https://forums.adafruit.com/viewtopic.php?f=58&t=128057
not working/hanging? 
i haven't tested IR extensively - but we recommend the NEC mini-remote since it's similar to many low cost remotes.

**Comment by mmoskal** [comment] 2017-12-20 16:40
The IR blocks do not support custom protocols of remotes. It only supports its own custom protocol. We'll need to investigate the hang though.

**Comment by abchatra** [comment] 2018-06-07 03:35
Closing as this is duplicate of https://github.com/Microsoft/pxt-adafruit/issues/649

**Closed** 2018-06-15 15:16 UTC
Labels: bug
