### ISSUE TITLE
The method "light.colors()" is missing when switched from "{}JAVASCRIPT" to "BLOCKS"

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt-adafruit#593] opened 2018-01-11 10:06 UTC
**Repro steps:**
• Navigate to https://makecode.adafruit.com/
• Switch to "{ }JAVASCRIPT" and copy below code on it
************************************************************
light.createStrip().setAll(light.colors(Colors.Red))
************************************************************
• Switch to "BLOCKS" and then go to "{ }JAVASCRIPT"
**Expected result:**
The light color still is red
**Actual result:**
The method "light.colors()" is missing.
![lights](https://user-images.githubusercontent.com/23497626/34819920-f547f556-f673-11e7-9e31-6923b92209d3.gif)

**Comment by samelhusseini** [comment] 2018-04-25 04:35
Dupe of https://github.com/Microsoft/pxt-adafruit/issues/674

**Closed by samelhusseini** 2018-04-25 04:35 UTC
