### ISSUE TITLE
Download Dialog doesn't go away

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-adafruit#628] opened 2018-02-09 18:57 UTC
Edge browser
Repro: click Download button, dialog pops up but stays up until you click the screen.

**Comment by pelikhan** [comment] 2018-02-09 21:33
That's by design since we've added the 3 steps download.

**Comment by samelhusseini** [comment] 2018-04-25 04:33
Closing by design

**Closed by samelhusseini** 2018-04-25 04:33 UTC
