### ISSUE TITLE
These two blocks don't have same selection menus

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-adafruit#681] opened 2018-04-11 07:59 UTC
**Repro steps:**
• Navigate to https://makecode.adafruit.com/beta#editor
• Click "ADVANCED" -> "PINS" and then drag blocks like below picture
• Click the selection menu
**Expected result:**
These two blocks should have same selection menus
**Actual result:**
These two blocks don't have same selection menus
![1](https://user-images.githubusercontent.com/23466737/38602888-9efcd4bc-3d5b-11e8-9c18-0d6f0f669f70.PNG)
![2](https://user-images.githubusercontent.com/23466737/38602893-a30f9cc4-3d5b-11e8-9450-08531e6dcdad.PNG)

**Comment by pelikhan** [comment] 2018-04-11 13:47
By design. Pin hav different capabilities.

________________________________

**Comment by Helen09** [comment] 2018-04-12 01:37
But if user wants to use these two blocks together, the block "console log value" don't have A0、SCL、SDA...

**Comment by samelhusseini** [comment] 2018-04-25 04:02
Closing by design.

**Closed by samelhusseini** 2018-04-25 04:02 UTC
